openapi: 3.0.4

info:
  title: DCM Kubernetes Cluster Specification
  description: |
    Provider-agnostic Kubernetes cluster specification.

    This schema defines minimal portable fields common across all Kubernetes
    distributions (OpenShift, EKS, GKE, AKS, self-managed, etc.).

    Platform-specific configuration (CNI type, authentication, ingress settings)
    should be specified via providerHints.
  version: v1alpha1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths: {}

components:
  schemas:
    ClusterSpec:
      type: object
      description: |
        Provider-agnostic Kubernetes cluster specification.

        Includes common fields (serviceType, metadata, providerHints)
        plus cluster-specific fields for version and node configuration.

        Providers translate this specification to their native format.
      allOf:
        - $ref: '../common.yaml#/components/schemas/CommonFields'
        - type: object
          required:
            - version
            - nodes
          properties:
            version:
              type: string
              description: |
                Kubernetes version (e.g., "1.29", "1.30", "1.31").

                Use standard Kubernetes version numbers. Providers translate
                to their distribution's version if needed (e.g., OpenShift
                providers map K8s 1.27 to OCP 4.14).
              example: "1.30"

            nodes:
              $ref: '#/components/schemas/Nodes'

          additionalProperties: true

    Nodes:
      type: object
      description: Node configuration
      required:
        - controlPlane
        - worker
      properties:
        controlPlane:
          $ref: '#/components/schemas/ControlPlaneNodes'
        worker:
          $ref: '#/components/schemas/WorkerNodes'
      additionalProperties: true

    ControlPlaneNodes:
      type: object
      description: |
        Control plane nodes configuration.
        Managed services (ACM (with Hypershift),EKS, GKE, AKS) may ignore these fields.
      required:
        - count
        - cpu
        - memory
        - storage
      properties:
        count:
          type: integer
          description: Number of control plane nodes (1, 3, or 5)
          enum:
            - 1
            - 3
            - 5
          example: 3
        cpu:
          type: integer
          description: CPU cores per control plane node
          minimum: 2
          example: 4
        memory:
          type: string
          description: Memory per control plane node with unit suffix
          pattern: '^[0-9]+(MB|GB|TB)$'
          example: 16GB
        storage:
          type: string
          description: Storage per control plane node with unit suffix
          pattern: '^[0-9]+(MB|GB|TB)$'
          example: 120GB
      additionalProperties: true

    WorkerNodes:
      type: object
      description: Worker nodes configuration
      required:
        - count
        - cpu
        - memory
        - storage
      properties:
        count:
          type: integer
          description: Number of worker nodes
          minimum: 1
          example: 3
        cpu:
          type: integer
          description: CPU cores per worker node
          minimum: 1
          example: 4
        memory:
          type: string
          description: Memory per worker node with unit suffix
          pattern: '^[0-9]+(MB|GB|TB)$'
          example: 8GB
        storage:
          type: string
          description: Storage per worker node with unit suffix
          pattern: '^[0-9]+(MB|GB|TB)$'
          example: 120GB
      additionalProperties: true
